
name: AI Code Assistant Automation

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  workflow_dispatch:  # Allows manual execution

jobs:
  run-ai-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install openai requests PyGithub

      - name: Run AI Code Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: python ai_code_assistant.py
